apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
      - name: userapi
        image: userapi:latest
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: userapi-service
spec:
  type: NodePort
  selector:
    app: userapi
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
